# Generated by Django 4.2.4 on 2023-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='news_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Dues',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
