# Generated by Django 4.2.4 on 2023-01-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_consultants_leadership_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=225)),
                ('team', models.TextField()),
            ],
        ),
    ]
