# Generated by Django 4.2.4 on 2024-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_postion_leadership_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default='News', max_length=10),
        ),
    ]
