# Generated by Django 4.2.4 on 2024-12-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultants',
            old_name='type_of_consult',
            new_name='area_of_expertise',
        ),
    ]
