# Generated by Django 4.2.4 on 2024-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_type_of_consult_consultants_area_of_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
