# Generated by Django 4.2.4 on 2023-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('mode_of_payment', models.CharField(choices=[('momo', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=4)),
                ('attendance', models.CharField(choices=[('observer', 'Observer'), ('speaker', 'Presenter')], max_length=10)),
                ('date_of_payment', models.DateField()),
            ],
        ),
    ]
